name: ROres
version: '1.0-SNAPSHOT'
main: org.tyjames03.rOres.ROres
api-version: '1.20'      # Adjusted to 1.20 for broader compatibility (change back to '1.21' if you are 100% on 1.21)
softdepend:
  - PlaceholderAPI
commands:
  rores:
    description: ROres command
    usage: /rores <give|reload>
    permission: rores.use
    permission-message: "You do not have permission to use this command."